version: "3.2"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "4001:4000"
      - "9568:9568"
    volumes:
      - ./:/app
      - _build:/app/_build
      - deps:/app/deps
    env_file: .env
    environment:
      - DB_HOST=db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["./run.sh"]
  db:
    image: postgres:12-alpine
    ports:
      - "5433:5432"
    expose:
      - "5433"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=motivus_wb_api_dev
      - POSTGRES_USER=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  admin:
    image: adminer
    depends_on:
      - db
    ports:
      - 8081:8080

volumes:
  db-data:
  deps:
  _build:
