version: "3.2"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        volumes:
            - ./:/app
        #env_file: .env
        environment:
            - MIX_ENV=prod
            - SECRET_KEY_BASE=mjdiowjdojewo
            - DB_PASSWORD=postgres
            - DB_NAME=motivus_wb_api_dev
            - DB_USER=postgres
            - DB_HOST=db
        command: ["./prod_run.sh"]
    db:
        image: postgres:12
        expose:
            - "5432"
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=motivus_wb_api_dev
            - POSTGRES_USER=postgres
        volumes:
            - db-data:/var/lib/postgresql/data
    admin:
        image: adminer
        depends_on:
            - db
        ports:
            - 8081:8080

volumes:
    db-data:
