defmodule MotivusWbApi.Listeners do
  @moduledoc """
   Modules that act upon events generated by any of the entities relevant to task processing.

   Such entities can be, but not limited to:
   - Nodes
   - Threads
   - Tasks
   - Client

   Many instances of this listener can co-exist, the context provided can enable this, on the form of the process state.
   
   The context provided is used to work with a set of processes (pools and regisitries), and communicate using events thorugh a scope on a PubSub topic.
  """
end
