apiVersion: v1
kind: Service # Create service
metadata:
  name: postgres-wb # Sets the service name
  namespace: wb-api
  labels:
    app: postgres-wb # Defines app to create service for
spec:
  type: NodePort # Sets the service type
  ports:
    - port: 5432 # Sets the port to run the postgres-wb application
  selector:
    app: postgres-wb
