apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: motivus-home
profiles:
  - name: develop
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
      artifacts:
        - image: motivus/home
          docker:
            dockerfile: Dockerfile
            buildArgs:
              MARKETPLACE_API_URL: 'http://marketplace.api.motivus.cl'
    deploy:
      kubectl:
        manifests:
          - k8s/00-namespace.yaml
          - k8s/01-home-deployment.yml
          - k8s/03-home-service.yaml
          - k8s/04-ingress-rule.yaml
  - name: prod
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
      artifacts:
        - image: southamerica-west1-docker.pkg.dev/motivus-257216/motivus-repo/home
          docker:
            dockerfile: Dockerfile
            buildArgs:
              MARKETPLACE_API_URL: 'https://marketplace.api.motivus.cl'
    deploy:
      kubectl:
        manifests:
          - k8s/prod/00-namespace.yaml
          - k8s/prod/01-home-deployment.yml
          - k8s/prod/02-home-service.yaml
          - k8s/prod/03-ingress-rule.yaml
