# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/

singleuser:
  image:
    name: southamerica-west1-docker.pkg.dev/motivus-257216/jpn/pydampf
    tag: "4"
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            cp -rn /tmp/home-base/* /home/jovyan
  storage:
    capacity: 20Gi
    dynamic:
      storageClass: standard
scheduling:
  userPods:
    nodeAffinity:
      matchNodePurpose: require
hub:
  config:
    GitHubOAuthenticator:
      client_id: e81fd8f13d78b4a0f721
      client_secret: 4c7e22278a191b4eb728b7ecbf812bc37c7b787e
      oauth_callback_url: https://pydampf.motivus.cl/hub/oauth_callback
    JupyterHub:
      authenticator_class: github

proxy:
  https:
    enabled: true
    hosts:
      - pydampf.motivus.cl
    letsencrypt:
      contactEmail: sebastian@motivus.cl
