apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: node
profiles:
  - name: develop
  #build:
  #  artifacts:
  # - image: motivus/worker
  #  docker:
  #    dockerfile: Dockerfile
    deploy:
      kubectl:
        manifests:
        - k8s/00-namespace.yaml
        - k8s/01-motivus-worker.yaml
