# az postgres flexible-server create -g aks_test_clu_group -n wb-db --public-access all -l eastus --sku Standard_B1ms --tier Burstable

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: marketplace
  name: marketplace-deployment
  labels:
    app: marketplace-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace
  template:
    metadata:
      labels:
        app: marketplace
    spec:
      containers:
        - name: marketplace
          image: southamerica-west1-docker.pkg.dev/motivus-257216/motivus-repo/marketplace-api:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          env:
            - name: GITHUB_CLIENT_ID
              value: f2357420d89e533da6eb
            - name: GITHUB_CLIENT_SECRET
              value: e47b016733b859bc9523237a8ce2e927478b7a5a
            - name: GOOGLE_CLIENT_ID
              value: "907083709486-pubdmk40go3n76brdoevu5iklsgmrus5.apps.googleusercontent.com"
            - name: GOOGLE_CLIENT_SECRET
              value: 4Atimx7SM-Q98mtNFWNBLjst
            - name: DB_HOST
              value: "34.176.5.107"
            - name: DB_USER
              value: api-admin
            - name: DB_PASSWORD
              value: IVolP4X~bQSqN3mX
            - name: DB_NAME
              value: motivus_marketplace_api_prod
            - name: AWS_ACCESS_KEY_ID
              value: AKIAXTPV4Y3S3OY6WC73
            - name: AWS_SECRET_ACCESS_KEY
              value: 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
            - name: AWS_S3_BUCKET_NAME
              value: motivus-marketplace
            - name: AWS_S3_HOST
              value: motivus-marketplace.s3.amazonaws.com
            - name: AWS_REGION
              value: us-east-1
            - name: MIX_ENV
              value: prod
            - name: PORT
              value: "80"
            - name: SPA_OAUTH_REDIRECT_URI
              value: https://motivus.cl/auth/
            - name: SECRET_KEY_BASE
              value: o3LZY1dfsKQN4aLKanqCn8zFkcwDN/8UVPxfMs629+x4iDKdluhtaFUxZ9t54TPH
